### ISSUE TITLE
new release timeline?

### ISSUE THREAD

**Issue by benswift** [bennylope/pydiscourse#14]
Hey there,

`v0.7.0` on [PyPI](https://pypi.org/project/pydiscourse/#history) is super-old, and there are a bunch of goodies in the `master` branch here I'd love to have access to. Any idea when there's a plan for an updated PyPI package?

**Comment by goetzk** [comment]
I've found this (and https://github.com/amolinaalvarez/pydiscourse ) both install with pip -e quite happily, if that work around is allowed in your projects.

(FTR: I agree with the thrust of your issue)

**Comment by bennylope** [comment]
This was way overdue, it's up on PyPI now as version 0.8.0.

![Live](https://media.giphy.com/media/CEC45sbOpCoEg/giphy.gif)
