### ISSUE TITLE
Deadlink under the todo section on docs. 

### ISSUE THREAD

**Issue by logankilpatrick** [bennylope/pydiscourse#22]
https://discourse.readthedocs.io/en/latest/develop.html#todo

**Comment by logankilpatrick** [comment]
Was removed per: https://github.com/discourse/discourse_api/pull/173

**Comment by bennylope** [comment]
Nice catch! Fixed with 802f0185196db3366d740663a2c9ac136d77ea05 in which I used the Discourse issue ID instead of this one.
