### ISSUE TITLE
Allow redirects for requests

### ISSUE THREAD

**Issue by gar1t** [bennylope/pydiscourse#32]
Are you aware of any issues when supporting redirects from the Discourse server? In your call to `requests.request()` you explicitly set `allow_redirects` to `False`. This prevents topic lookup by path only (omitting the ID).

I think a number of functions could make ID optional using the server redirect to resolve as needed.

**Comment by bennylope** [comment]
> Are you aware of any issues when supporting redirects from the Discourse server?

I'm not aware of any, it was added here 0cef55a02f764f7118e107827900763c8f388494 probably because it seemed sensible? 

Don't see any reasons why this couldn't be changed.

**Comment by gar1t** [comment]
I'm working on a fork atm and will try to apply this redirect support where I can spot opportunities. E.g. `client.topic(slug)` where `id` can be omitted seems to work. When I have something presentable I'll open a PR for review.

**Comment by abkfenris** [comment]
I've created a PR that takes a swing at allowing redirects for certain methods #34 .

I found this issue with `client.category_topics(id)` as `/c/{id}.json` now redirects to `/c/{category_slug}.json`.

My PR implements this by allowing `request_kwargs` to be passed to the HTTP verb methods, which pass it along to `client._request` where they can override the default keyword arguments for `request.request`.
