### ISSUE TITLE
Version 1.1.1 not available at PyPi

### ISSUE THREAD

**Issue by vmanilo** [bennylope/pydiscourse#42]
Hello, guys

I see you've been releasing new version with tag 1.1.1, but for some reason it didn't appear at pypi
there is a fix for the issue **pydiscourse.exceptions.DiscourseClientError: Payload Too Large**
and currently it's not available

**Comment by citadelgrad** [comment]
@bennylope Can you help with this?

**Comment by bennylope** [comment]
https://pypi.org/project/pydiscourse/1.1.1/

And see #43 folks!
