### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by bennylope** [bennylope/pydiscourse#45]
Should add test support for Python 3.9 and drop support for everything _prior_ to Python 3.6.

**Comment by TonnyRobins** [comment]
Thanks for sharing. [best skateboard Grip Tape](https://skateguides.com/best-skateboard-grip-tape/)

**Comment by goetzk** [comment]
Seems to have been done in commits bbe216ef8c6e744903bf1124024a6607d42d6515 and ef5f8523d8db8f3fb041d8045d2093b20df0d682 .
