### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

### ISSUE THREAD

**Issue by dgadiraju** [bennylope/pydiscourse#48]
I tried to follow the instructions provided to connect to my https website. It is failing with **SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
**

Here is the sample code as per the instructions provided.

from pydiscourse import DiscourseClient
client = DiscourseClient(
        'https://discuss.itversity.com',
        api_username='dgadiraju',
        api_key='api_key_with_single_user_and_global_permissions')

**Comment by goetzk** [comment]
The certificate is probably not in your local certificate store, it's missing on my test computer.
Karl

* Expire in 200 ms for 4 (transfer 0x5650938eaf50)
* Connected to discuss.itversity.com (104.131.11.154) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1614 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

On 28 December 2020 2:53:28 am AEDT, Durga Gadiraju <notifications@github.com> wrote:
>I tried to follow the instructions provided to connect to my https
>website. It is failing with **SSLError: [SSL:
>CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
>**
>
>Here is the sample code as per the instructions provided.
>
>from pydiscourse import DiscourseClient
>client = DiscourseClient(
>        'https://discuss.itversity.com',
>        api_username='dgadiraju',
>        api_key='api_key_with_single_user_and_global_permissions')
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bennylope/pydiscourse/issues/48

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goetzk** [comment]
@dgadiraju - please reply here if you require further assistance.
