### ISSUE TITLE
Bump pypi 1.1.3 ?

### ISSUE THREAD

**Issue by weber-s** [bennylope/pydiscourse#52]
Hello!

Thank you for this module.

Is it possible to update the pypi version to include the latest change in master ? Notably, I would need the `category_latest_topics`.

Thanks again!

**Comment by goetzk** [comment]
@bennylope I was going to tag a new release but given your recent slew of changes I'm wondering if we should go with 1.2.0 or if you support going with 1.1.3.

**Comment by bennylope** [comment]
@goetzk at least 1.2.0 since this drops support for older versions of Python!

**Comment by bennylope** [comment]
https://pypi.org/project/pydiscourse/
