### ISSUE TITLE
Please merge features added by Alvaro Molina Alvarez

### ISSUE THREAD

**Issue by goetzk** [bennylope/pydiscourse#8]
Hi,
I'm currently using your packages from pip (thanks!), but I've had to write a bunch of code to work around missing functionality - mainly related to json . Alvaro Molina Alvarez (@amolinaalvarez) has added a number of features including json support that I'm hoping you will be willing to merge. The diff is substantial but easy to follow and includes support for API calls currently not provided in your tree.

https://github.com/bennylope/pydiscourse/compare/master...amolinaalvarez:master

thanks,
kk

**Comment by bennylope** [comment]
It looks like there are some great additions and I'd be happy to get them in here. Two big requirements though:

1. No breaking changes (without very good reasons, plus documentation)
2. A pull request

We're a little past this, but there are some guidelines in the [contributing guide](https://github.com/bennylope/pydiscourse/blob/master/CONTRIBUTING.rst), and as long as the PR documents the discrete features, we can probably work with that.

Okay, so, breaking changes! I did a very quick review and noticed at least one breaking change that, if left in place, is a deal breaker. It's in [pydiscourse/sso.py](https://github.com/bennylope/pydiscourse/compare/master...amolinaalvarez:master#diff-fadc68ce18cbb07824922c4934836d17)

Adding required arguments, like so, is a breaking change:

```diff
-def sso_redirect_url(nonce, secret, email, external_id, username, **kwargs):
+def sso_redirect_url(nonce, secret, email, external_id, username, name, avatar_url, bio, **kwargs):
```

I understand the value of having that data, but not everyone needs that data, and other people are using this _without including those data_. Which means if we include this, i.e. add new required arguments, then we've broken integrations for anyone using SSO who wants to use other features.

**Comment by goetzk** [comment]
I've pushed three branches made from cherry picking changes by @amolinaalvarez , two of which I've turned in to pull requests (#9 and #10).

**Comment by goetzk** [comment]
Update:
https://github.com/bennylope/pydiscourse/pull/10/commits/9fbfa3906004016080d296b15a1de657933c92c0
* site_settings had changed signature and has been removed from the branch in 
006b7d4

**Comment by goetzk** [comment]
Thanks for merging those branches!
I'm closing this now, but if @amolinaalvarez updates his branch I may try and merge in some other bits - He still has my corrected suspend() which isn't currently in this version (and is currently broken in this version - https://github.com/amolinaalvarez/pydiscourse/pull/1 ).

kk
